name: flutter_test_1
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.2.0
  hive_flutter: ^1.1.0
  flutter_screenutil: ^5.9.3
  go_router: ^17.0.1
  flutter_svg: ^2.2.3

flutter_test:
  sdk: flutter
flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/svgs/
    - assets/pdfs/
    - assets/lotties/

# flutter_launcher_icons:
#   android: true
#   ios: true
#   image_path: "assets/images/auth_bg.png"
